#!/bin/sh

# export LANG="en_US.UTF-8"
# export LC_COLLATE="en_US.UTF-8"
# export LC_CTYPE="en_US.UTF-8"
# export LC_MESSAGES="en_US.UTF-8"
# export LC_MONETARY="en_US.UTF-8"
# export LC_NUMERIC="en_US.UTF-8"
# export LC_TIME="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# pip install virtualenv
# pip3 install virtualenv

# virtualenv ./venv
# . ./venv/bin/activate

# brew install python3 cairo pango gdk-pixbuf libffi
# pip install WeasyPrint
# pip3 install WeasyPrint


# weasyprint --help

# weasyprint -e UTF-8 resume.html resume.pdf
# weasyprint -e UTF-8 -s modulenew/resume/bt_index/resumepdf.css  resume.html resume.pdf





# pip install pdfkit
# brew install caskroom/cask/wkhtmltopdf

# python -m SimpleHTTPServer

cd $(dirname $0);
pwd
python $(dirname $0)/pdf_builder.py




